### ISSUE TITLE
Nuget package ?

### ISSUE THREAD

**Issue by SeleDreams** [FomTarro/VTS-Sharp#31]
I feel like it would be easier to use the library by making a nuget package, this way it could directly be automatically downloaded and setup during build

**Comment by FomTarro** [comment]
I have never used Nuget before so I don't know the first thing about doing that. I assume it would require two packages? One for just `Core` and one for `Unity`? Or would it just be `Core` since Nuget isn't part of the Unity tool chain?

**Comment by SeleDreams** [comment]
I think just one for core would be enough

**Comment by yutamago** [comment]
I went ahead and made a NuGet wrapper for VTS-Sharp, intended to be used _**outside of Unity**_.
It only includes the core parts of VTS-Sharp and leaves out the Unity-specific implementations and examples.

https://github.com/yutamago/VTS-Sharp-Core

The readme includes an example of a console application.
I've been using this in a ASP.NET Core 7.0 project, controlling VTS through a REST API.

I'm not suuuper active on Github, so if you want to maintain it, go ahead and make it your own. :)

**Comment by FomTarro** [comment]
Wish fulfilled. Thank you, @yutamago! 

https://www.nuget.org/packages/VTS-Sharp/2.1.0

Closing this issue now.
