### ISSUE TITLE
I am very sorry for what I did, but I don't want to let go of the current problems (I'm sorry🥲)

### ISSUE THREAD

**Issue by AmaneOjakasa** [FomTarro/VTS-Sharp#44]
I want to adjust our understanding that what I did was against the rules, but my plan is that I see the growth of the Vtube industry in my country. But!! New Vtubers have limited financial resources, so I did this to reduce the over-reliance on the Apple ecosystem, so that new Vtubers have more spending options so that they don't have financial problems in the future. (This is something that I have never told anyone🥲)

**Comment by yutamago** [comment]
You realize that you just notified every single person following this repo?

I have no clue what this is about, but this does not belong in the issues. If there is something Apple-related that bugs you, feel free to open a proper issue about it.

**Comment by AmaneOjakasa** [comment]
Please delete all the parts I posted so that the problem does not get worse in the future 🥲

**Comment by FomTarro** [comment]
I am not a moderator in the VTube Studio Discord, nor do I have any influence on moderation decisions. And, even if I did, this is not an appropriate way to contest those decisions, for the reasons Yuta said.
