### ISSUE TITLE
ParameterValueResponse bug

### ISSUE THREAD

**Issue by Nynecrest** [FomTarro/VTS-Sharp#7]
In the VTSWebSocket.cs, the ProcessResponses method is missing a case for ParameterValueResponse.

**Comment by FomTarro** [comment]
Sorry about the delay on this, I was expecting GitHub to email me but it seems that it hasn't. Should be resolved now in release 1.2.2 https://github.com/FomTarro/VTS-Sharp/releases/tag/v1.2.2
